import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Lottie from "lottie-react-web";
import checkAnimation from "../lottie/check.json";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lottie playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Lottie Playground</h1>
        <Lottie
          options={{
            animationData: checkAnimation,
            loop: true,
          }}
        />
        <Link href="/loading">View loading animation</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        ></a>
      </footer>
    </div>
  );
}
