import { useEffect, useState } from "react";
import Head from "next/head";
import loadingAnimation from "../../lottie/loading.json";
import styles from "../../styles/Home.module.css";
import BlogPost from "./BlogPost";
import Lottie from "lottie-react-web";

export default function Loading() {
  const [loading, setLoading] = useState(true);
  const [blogPosts, setBlogPosts] = useState([]);

  useEffect(() => {
    if (blogPosts === []) getBlogPosts();
  }, [blogPosts]);

  async function getBlogPosts() {
    const posts = await getMediumArticles();
    setBlogPosts(posts);
    setLoading(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Loading Animation</h1>
        {loading ? (
          <Lottie
            options={{
              animationData: loadingAnimation,
              loop: true,
            }}
          />
        ) : (
          blogPosts.map((post) => <BlogPost {...post} key={post.datePosted} />)
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/rachelrly"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Rachel Reilly
        </a>
      </footer>
    </div>
  );
}

export async function getMediumArticles() {
  try {
    const response = await fetch(`${process.env.API_URL}/api/feed`);
    const json = await response.json();
    return json;
  } catch (error) {
    console.error("Error fetching Medium articles: ", error?.message);
  }
}
